CREATE TABLE IF NOT EXISTS `alert` (
  `id` Serial NOT NULL,
  `version` Int64 NOT NULL,
  `dashboard_id` Int64 NOT NULL,
  `panel_id` Int64 NOT NULL,
  `org_id` Int64 NOT NULL,
  `name` Text NOT NULL,
  `message` Text NOT NULL,
  `state` Text NOT NULL,
  `settings` Text NOT NULL,
  `frequency` Int64 NOT NULL,
  `handler` Int64 NOT NULL,
  `severity` Text NOT NULL,
  `silenced` Int64 NOT NULL,
  `execution_error` Text NOT NULL,
  `eval_data` Text,
  `eval_date` Datetime64,
  `new_state_date` Datetime64 NOT NULL,
  `state_changes` Int64 NOT NULL,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `for` Int64,
  PRIMARY KEY (`id`),
  INDEX `IDX_alert_org_id_id` GLOBAL SYNC ON (`org_id`, `id`),
  INDEX `IDX_alert_state` GLOBAL SYNC ON (`state`),
  INDEX `IDX_alert_dashboard_id` GLOBAL SYNC ON (`dashboard_id`)
);
