CREATE TABLE IF NOT EXISTS `alert_rule_version` (
  `id` Serial NOT NULL,
  `rule_org_id` Int64 NOT NULL,
  `rule_uid` Text NOT NULL,
  `rule_namespace_uid` Text NOT NULL,
  `rule_group` Text NOT NULL,
  `parent_version` Int64 NOT NULL,
  `restored_from` Int64 NOT NULL,
  `version` Int64 NOT NULL,
  `created` Datetime64 NOT NULL,
  `title` Text NOT NULL,
  `condition` Text NOT NULL,
  `data` Text NOT NULL,
  `interval_seconds` Int64 NOT NULL,
  `no_data_state` Text NOT NULL DEFAULT 'NoData',
  `exec_err_state` Text NOT NULL DEFAULT 'Alerting',
  `for` Int64 NOT NULL DEFAULT 0,
  `annotations` Text,
  `labels` Text,
  `rule_group_idx` Int64 NOT NULL DEFAULT 1,
  `is_paused` Uint8 NOT NULL DEFAULT 0,
  `notification_settings` Text,
  `record` Text,
  `metadata` Text,
  `created_by` Text,
  `rule_guid` Text NOT NULL DEFAULT '',
  `keep_firing_for` Int64 NOT NULL DEFAULT 0,
  `missing_series_evals_to_resolve` Int64,
  PRIMARY KEY (`id`),
  INDEX `IDX_alert_rule_version_rule_org_id_rule_namespace_uid_rule_group` GLOBAL SYNC ON (`rule_org_id`, `rule_namespace_uid`, `rule_group`),
  INDEX `UQE_alert_rule_version_rule_org_id_rule_uid_rule_guid_version` GLOBAL UNIQUE SYNC ON (`rule_org_id`, `rule_uid`, `rule_guid`, `version`),
  INDEX `UQE_alert_rule_version_rule_guid_version` GLOBAL UNIQUE SYNC ON (`rule_guid`, `version`),
);
