CREATE TABLE IF NOT EXISTS `dashboard_acl` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `dashboard_id` Int64 NOT NULL,
  `user_id` Int64,
  `team_id` Int64,
  `permission` Int64 NOT NULL DEFAULT 4,
  `role` Text,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_dashboard_acl_dashboard_id` GLOBAL SYNC ON (`dashboard_id`),
  INDEX `UQE_dashboard_acl_dashboard_id_user_id` GLOBAL UNIQUE SYNC ON (`dashboard_id`, `user_id`),
  INDEX `UQE_dashboard_acl_dashboard_id_team_id` GLOBAL UNIQUE SYNC ON (`dashboard_id`, `team_id`),
  INDEX `IDX_dashboard_acl_user_id` GLOBAL SYNC ON (`user_id`),
  INDEX `IDX_dashboard_acl_team_id` GLOBAL SYNC ON (`team_id`),
  INDEX `IDX_dashboard_acl_org_id_role` GLOBAL SYNC ON (`org_id`, `role`),
  INDEX `IDX_dashboard_acl_permission` GLOBAL SYNC ON (`permission`),
);
