CREATE TABLE IF NOT EXISTS `dashboard` (
  `id` Serial NOT NULL,
  `version` Int64 NOT NULL,
  `slug` Text NOT NULL,
  `title` Text NOT NULL,
  `data` Text NOT NULL,
  `org_id` Int64 NOT NULL,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `updated_by` Int64,
  `created_by` Int64,
  `gnet_id` Int64,
  `plugin_id` Text,
  `folder_id` Int64 NOT NULL DEFAULT 0,
  `is_folder` Uint8 NOT NULL DEFAULT 0,
  `has_acl` Int64 NOT NULL DEFAULT 0,
  `uid` Text,
  `is_public` Uint8 NOT NULL DEFAULT 0,
  `deleted` Datetime64,
  `api_version` Text,
  `folder_uid` Text,
  PRIMARY KEY (`id`),
  INDEX `IDX_dashboard_org_id` GLOBAL SYNC ON (`org_id`),
  INDEX `IDX_dashboard_gnet_id` GLOBAL SYNC ON (`gnet_id`),
  INDEX `IDX_dashboard_org_id_plugin_id` GLOBAL SYNC ON (`org_id`, `plugin_id`),
  INDEX `UQE_dashboard_org_id_uid` GLOBAL UNIQUE SYNC ON (`org_id`, `uid`),
  INDEX `IDX_dashboard_title` GLOBAL SYNC ON (`title`),
  INDEX `IDX_dashboard_is_folder` GLOBAL SYNC ON (`is_folder`),
  INDEX `IDX_dashboard_deleted` GLOBAL SYNC ON (`deleted`),
  INDEX `IDX_dashboard_org_id_folder_id_title` GLOBAL SYNC ON (`org_id`, `folder_id`, `title`),
);
