CREATE TABLE IF NOT EXISTS `team` (
  `id` Serial NOT NULL,
  `name` Text NOT NULL,
  `org_id` Int64 NOT NULL,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `uid` Text,
  `external_uid` Text,
  `is_provisioned` Uint8,
  `email` Text,
  PRIMARY KEY (`id`),
  INDEX `IDX_team_org_id` GLOBAL SYNC ON (`org_id`),
  INDEX `UQE_team_org_id_name` GLOBAL UNIQUE SYNC ON (`org_id`, `name`),
  INDEX `UQE_team_org_id_uid` GLOBAL UNIQUE SYNC ON (`org_id`, `uid`),
);
