CREATE TABLE IF NOT EXISTS `temp_user` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `version` Int64 NOT NULL,
  `email` Text NOT NULL,
  `name` Text,
  `role` Text,
  `code` Text NOT NULL,
  `status` Text NOT NULL,
  `invited_by_user_id` Int64,
  `email_sent` Int64 NOT NULL,
  `email_sent_on` Datetime64,
  `remote_addr` Text,
  `created` Int64 NOT NULL DEFAULT 0,
  `updated` Int64 NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `IDX_temp_user_email` GLOBAL SYNC ON (`email`),
  INDEX `IDX_temp_user_org_id` GLOBAL SYNC ON (`org_id`),
  INDEX `IDX_temp_user_code` GLOBAL SYNC ON (`code`),
  INDEX `IDX_temp_user_status` GLOBAL SYNC ON (`status`),
);
