CREATE TABLE IF NOT EXISTS `alert_rule` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `title` Text NOT NULL,
  `condition` Text NOT NULL,
  `data` Text NOT NULL,
  `updated` Datetime64 NOT NULL,
  `interval_seconds` Int64 NOT NULL DEFAULT 60,
  `version` Int64 NOT NULL DEFAULT 0,
  `uid` Text NOT NULL,
  `namespace_uid` Text NOT NULL,
  `rule_group` Text NOT NULL,
  `no_data_state` Text NOT NULL DEFAULT 'NoData',
  `exec_err_state` Text NOT NULL DEFAULT 'Alerting',
  `for` Int64 NOT NULL DEFAULT 0,
  `annotations` Text,
  `labels` Text,
  `dashboard_uid` Text,
  `panel_id` Int64,
  `rule_group_idx` Int64 NOT NULL DEFAULT 1,
  `is_paused` Bool NOT NULL DEFAULT false,
  `notification_settings` Text,
  `record` Text,
  `metadata` Text,
  `updated_by` Text,
  `guid` Text NOT NULL DEFAULT '',
  `keep_firing_for` Int64 NOT NULL DEFAULT 0,
  `missing_series_evals_to_resolve` Int64,
  PRIMARY KEY (`id`),
  INDEX `UQE_alert_rule_org_id_uid` GLOBAL UNIQUE SYNC ON (`org_id`, `uid`),
  INDEX `IDX_alert_rule_org_id_namespace_uid_rule_group` GLOBAL SYNC ON (`org_id`, `namespace_uid`, `rule_group`),
  INDEX `IDX_alert_rule_org_id_dashboard_uid_panel_id` GLOBAL SYNC ON (`org_id`, `dashboard_uid`, `panel_id`),
  INDEX `UQE_alert_rule_guid` GLOBAL UNIQUE SYNC ON (`guid`),
);
