CREATE TABLE IF NOT EXISTS `annotation` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `alert_id` Int64,
  `user_id` Int64,
  `dashboard_id` Int64,
  `panel_id` Int64,
  `category_id` Int64,
  `type` Text NOT NULL,
  `title` Text NOT NULL,
  `text` Text NOT NULL,
  `metric` Text,
  `prev_state` Text NOT NULL,
  `new_state` Text NOT NULL,
  `data` Text NOT NULL,
  `epoch` Int64 NOT NULL,
  `region_id` Int64,
  `tags` Text,
  `created` Int64,
  `updated` Int64,
  `epoch_end` Int64 NOT NULL DEFAULT 0,
  `dashboard_uid` Text,
  PRIMARY KEY (`id`),
  INDEX `IDX_annotation_org_id_alert_id` GLOBAL SYNC ON (`org_id`, `alert_id`),
  INDEX `IDX_annotation_org_id_type` GLOBAL SYNC ON (`org_id`, `type`),
  INDEX `IDX_annotation_org_id_created` GLOBAL SYNC ON (`org_id`, `created`),
  INDEX `IDX_annotation_org_id_updated` GLOBAL SYNC ON (`org_id`, `updated`),
  INDEX `IDX_annotation_org_id_dashboard_id_epoch_end_epoch` GLOBAL SYNC ON (`org_id`, `dashboard_id`, `epoch_end`, `epoch`),
  INDEX `IDX_annotation_org_id_epoch_end_epoch` GLOBAL SYNC ON (`org_id`, `epoch_end`, `epoch`),
  INDEX `IDX_annotation_alert_id` GLOBAL SYNC ON (`alert_id`),
);
