CREATE TABLE IF NOT EXISTS `api_key` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `name` Text NOT NULL,
  `key` Text NOT NULL,
  `role` Text NOT NULL,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `expires` Int64,
  `service_account_id` Int64,
  `last_used_at` Datetime64,
  `is_revoked` Bool DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX `IDX_api_key_org_id` GLOBAL SYNC ON (`org_id`),
  INDEX `UQE_api_key_key` GLOBAL UNIQUE SYNC ON (`key`),
  INDEX `UQE_api_key_org_id_name` GLOBAL UNIQUE SYNC ON (`org_id`, `name`),
);
