CREATE TABLE IF NOT EXISTS `dashboard_snapshot` (
  `id` Serial NOT NULL,
  `name` Text NOT NULL,
  `key` Text NOT NULL,
  `delete_key` Text NOT NULL,
  `org_id` Int64 NOT NULL,
  `user_id` Int64 NOT NULL,
  `external` Int64 NOT NULL,
  `external_url` Text NOT NULL,
  `dashboard` Text NOT NULL,
  `expires` Datetime64 NOT NULL,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `external_delete_url` Text,
  `dashboard_encrypted` Bytes,
  PRIMARY KEY (`id`),
  INDEX `UQE_dashboard_snapshot_key` GLOBAL UNIQUE SYNC ON (`key`),
  INDEX `UQE_dashboard_snapshot_delete_key` GLOBAL UNIQUE SYNC ON (`delete_key`),
  INDEX `IDX_dashboard_snapshot_user_id` GLOBAL SYNC ON (`user_id`),
);
