CREATE TABLE IF NOT EXISTS `data_source` (
  `id` Serial NOT NULL,
  `org_id` Int64 NOT NULL,
  `version` Int64 NOT NULL,
  `type` Text NOT NULL,
  `name` Text NOT NULL,
  `access` Text NOT NULL,
  `url` Text NOT NULL,
  `password` Text,
  `user` Text,
  `database` Text,
  `basic_auth` Int64 NOT NULL,
  `basic_auth_user` Text,
  `basic_auth_password` Text,
  `is_default` Bool NOT NULL,
  `json_data` Text,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `with_credentials` Int64 NOT NULL DEFAULT 0,
  `secure_json_data` Text,
  `read_only` Int64,
  `uid` Text NOT NULL,
  `is_prunable` Bool DEFAULT false,
  `api_version` Text,
  PRIMARY KEY (`id`),
  INDEX `IDX_data_source_org_id` GLOBAL SYNC ON (`org_id`),
  INDEX `UQE_data_source_org_id_name` GLOBAL UNIQUE SYNC ON (`org_id`, `name`),
  INDEX `UQE_data_source_org_id_uid` GLOBAL UNIQUE SYNC ON (`org_id`, `uid`),
  INDEX `IDX_data_source_org_id_is_default` GLOBAL SYNC ON (`org_id`, `is_default`),
);
