CREATE TABLE IF NOT EXISTS `secret_secure_value` (
  `guid` Text NOT NULL,
  PRIMARY KEY (`guid`),
  `name` Text NOT NULL,
  `namespace` Text NOT NULL,
  `annotations` Text,
  `labels` Text,
  `created` Int64 NOT NULL,
  `created_by` Text NOT NULL,
  `updated` Int64 NOT NULL,
  `updated_by` Text NOT NULL,
  `external_id` Text NOT NULL,
  `active` Int64 NOT NULL,
  `version` Int64 NOT NULL,
  `description` Text NOT NULL,
  `keeper` Text,
  `decrypters` Text,
  `ref` Text,
  `owner_reference_api_group` Text,
  `owner_reference_api_version` Text,
  `owner_reference_kind` Text,
  `owner_reference_name` Text,
  `lease_token` Text,
  `lease_created` Int64 NOT NULL DEFAULT 0,
  INDEX `UQE_secret_secure_value_namespace_name_version_active` GLOBAL UNIQUE SYNC ON (`namespace`, `name`, `version`, `active`),
  INDEX `UQE_secret_secure_value_namespace_name_version` GLOBAL UNIQUE SYNC ON (`namespace`, `name`, `version`),
  INDEX `IDX_secret_secure_value_namespace_active_updated` GLOBAL SYNC ON (`namespace`, `active`, `updated`),
  INDEX `IDX_secret_secure_value_lease_token` GLOBAL SYNC ON (`lease_token`),
  INDEX `IDX_secret_secure_value_lease_created` GLOBAL SYNC ON (`lease_created`),
);
