CREATE TABLE IF NOT EXISTS `user` (
  `id` Serial NOT NULL,
  `version` Int64 NOT NULL,
  `login` Text NOT NULL,
  `email` Text NOT NULL,
  `name` Text,
  `password` Text,
  `salt` Text,
  `rands` Text,
  `company` Text,
  `org_id` Int64 NOT NULL,
  `is_admin` Bool NOT NULL,
  `email_verified` Bool,
  `theme` Text,
  `created` Datetime64 NOT NULL,
  `updated` Datetime64 NOT NULL,
  `help_flags1` Int64 NOT NULL DEFAULT 0,
  `last_seen_at` Datetime64,
  `is_disabled` Bool NOT NULL DEFAULT false,
  `is_service_account` Bool DEFAULT false,
  `uid` Text,
  `is_provisioned` Bool NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX `UQE_user_login` GLOBAL UNIQUE SYNC ON (`login`),
  INDEX `UQE_user_email` GLOBAL UNIQUE SYNC ON (`email`),
  INDEX `IDX_user_login_email` GLOBAL SYNC ON (`login`, `email`),
  INDEX `UQE_user_uid` GLOBAL UNIQUE SYNC ON (`uid`),
  INDEX `IDX_user_is_service_account_last_seen_at` GLOBAL SYNC ON (`is_service_account`, `last_seen_at`),
);
