CREATE TABLE IF NOT EXISTS `user_auth_token` (
  `id` Serial NOT NULL,
  `user_id` Int64 NOT NULL,
  `auth_token` Text NOT NULL,
  `prev_auth_token` Text NOT NULL,
  `user_agent` Text NOT NULL,
  `client_ip` Text NOT NULL,
  `auth_token_seen` Int64 NOT NULL,
  `seen_at` Int64,
  `rotated_at` Int64 NOT NULL,
  `created_at` Int64 NOT NULL,
  `updated_at` Int64 NOT NULL,
  `revoked_at` Int64,
  `external_session_id` Int64,
  PRIMARY KEY (`id`),
  INDEX `UQE_user_auth_token_auth_token` GLOBAL UNIQUE SYNC ON (`auth_token`),
  INDEX `UQE_user_auth_token_prev_auth_token` GLOBAL UNIQUE SYNC ON (`prev_auth_token`),
  INDEX `IDX_user_auth_token_user_id` GLOBAL SYNC ON (`user_id`),
  INDEX `IDX_user_auth_token_revoked_at` GLOBAL SYNC ON (`revoked_at`),
);
