package ydb

import (
	"context"
	"embed"
	"fmt"
	"strings"
	"text/template"

	"github.com/ydb-platform/ydb-go-sdk/v3"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xstring"
)

//go:embed snapshot/*.sql
var snapshotFS embed.FS

type sqlFile struct {
	name    string
	content string
}

const createMigrationLogTableTemplate = `
CREATE TABLE IF NOT EXISTS "{{.Name}}" (
  "id" Serial NOT NULL,
  "migration_id" Text NOT NULL,
  "sql" Text,
  "success" Bool NOT NULL,
  "error" Text,
  "timestamp" Datetime64,
  PRIMARY KEY ("migration_id"),
);
`

const upsertMigrationLogData = `
UPSERT INTO "{{.Name}}" ("migration_id", "success")
VALUES
  ('create migration_log table',true),
  ('create user table',true),
  ('add unique index user.login',true),
  ('add unique index user.email',true),
  ('drop index UQE_user_login - v1',true),
  ('drop index UQE_user_email - v1',true),
  ('Rename table user to user_v1 - v1',true),
  ('create user table v2',true),
  ('create index UQE_user_login - v2',true),
  ('create index UQE_user_email - v2',true),
  ('copy data_source v1 to v2',true),
  ('Drop old table user_v1',true),
  ('Add column help_flags1 to user table',true),
  ('Update user table charset',true),
  ('Add last_seen_at column to user',true),
  ('Add missing user data',true),
  ('Add is_disabled column to user',true),
  ('Add index user.login/user.email',true),
  ('Add is_service_account column to user',true),
  ('Update is_service_account column to nullable',true),
  ('Add uid column to user',true),
  ('Update uid column values for users',true),
  ('Make sure users uid are set',true),
  ('Add unique index user_uid',true),
  ('Add is_provisioned column to user',true),
  ('update login field with orgid to allow for multiple service accounts with same name across orgs',true),
  ('update service accounts login field orgid to appear only once',true),
  ('update login and email fields to lowercase',true),
  ('update login and email fields to lowercase2',true),
  ('Add index on user.is_service_account and user.last_seen_at',true),
  ('create temp user table v1-7',true),
  ('create index IDX_temp_user_email - v1-7',true),
  ('create index IDX_temp_user_org_id - v1-7',true),
  ('create index IDX_temp_user_code - v1-7',true),
  ('create index IDX_temp_user_status - v1-7',true),
  ('Update temp_user table charset',true),
  ('drop index IDX_temp_user_email - v1',true),
  ('drop index IDX_temp_user_org_id - v1',true),
  ('drop index IDX_temp_user_code - v1',true),
  ('drop index IDX_temp_user_status - v1',true),
  ('Rename table temp_user to temp_user_tmp_qwerty - v1',true),
  ('create temp_user v2',true),
  ('create index IDX_temp_user_email - v2',true),
  ('create index IDX_temp_user_org_id - v2',true),
  ('create index IDX_temp_user_code - v2',true),
  ('create index IDX_temp_user_status - v2',true),
  ('copy temp_user v1 to v2',true),
  ('drop temp_user_tmp_qwerty',true),
  ('Set created for temp users that will otherwise prematurely expire',true),
  ('create star table',true),
  ('add unique index star.user_id_dashboard_id',true),
  ('Add column dashboard_uid in star',true),
  ('Add column org_id in star',true),
  ('Add column updated in star',true),
  ('add index in star table on dashboard_uid, org_id and user_id columns',true),
  ('create org table v1',true),
  ('create index UQE_org_name - v1',true),
  ('create org_user table v1',true),
  ('create index IDX_org_user_org_id - v1',true),
  ('create index UQE_org_user_org_id_user_id - v1',true),
  ('create index IDX_org_user_user_id - v1',true),
  ('Update org table charset',true),
  ('Update org_user table charset',true),
  ('Migrate all Read Only Viewers to Viewers',true),
  ('create dashboard table',true),
  ('add index dashboard.account_id',true),
  ('add unique index dashboard_account_id_slug',true),
  ('create dashboard_tag table',true),
  ('add unique index dashboard_tag.dasboard_id_term',true),
  ('drop index UQE_dashboard_tag_dashboard_id_term - v1',true),
  ('Rename table dashboard to dashboard_v1 - v1',true),
  ('create dashboard v2',true),
  ('create index IDX_dashboard_org_id - v2',true),
  ('create index UQE_dashboard_org_id_slug - v2',true),
  ('copy dashboard v1 to v2',true),
  ('drop table dashboard_v1',true),
  ('alter dashboard.data to mediumtext v1',true),
  ('Add column updated_by in dashboard - v2',true),
  ('Add column created_by in dashboard - v2',true),
  ('Add column gnetId in dashboard',true),
  ('Add index for gnetId in dashboard',true),
  ('Add column plugin_id in dashboard',true),
  ('Add index for plugin_id in dashboard',true),
  ('Add index for dashboard_id in dashboard_tag',true),
  ('Update dashboard table charset',true),
  ('Update dashboard_tag table charset',true),
  ('Add column folder_id in dashboard',true),
  ('Add column isFolder in dashboard',true),
  ('Add column has_acl in dashboard',true),
  ('Add column uid in dashboard',true),
  ('Update uid column values in dashboard',true),
  ('Add unique index dashboard_org_id_uid',true),
  ('Remove unique index org_id_slug',true),
  ('Update dashboard title length',true),
  ('Add unique index for dashboard_org_id_title_folder_id',true),
  ('create dashboard_provisioning',true),
  ('Rename table dashboard_provisioning to dashboard_provisioning_tmp_qwerty - v1',true),
  ('create dashboard_provisioning v2',true),
  ('create index IDX_dashboard_provisioning_dashboard_id - v2',true),
  ('create index IDX_dashboard_provisioning_dashboard_id_name - v2',true),
  ('copy dashboard_provisioning v1 to v2',true),
  ('drop dashboard_provisioning_tmp_qwerty',true),
  ('Add check_sum column',true),
  ('Add index for dashboard_title',true),
  ('delete tags for deleted dashboards',true),
  ('delete stars for deleted dashboards',true),
  ('Add index for dashboard_is_folder',true),
  ('Add isPublic for dashboard',true),
  ('Add deleted for dashboard',true),
  ('Add index for deleted',true),
  ('Add column dashboard_uid in dashboard_tag',true),
  ('Add column org_id in dashboard_tag',true),
  ('Add missing dashboard_uid and org_id to dashboard_tag',true),
  ('Add apiVersion for dashboard',true),
  ('Add index for dashboard_uid on dashboard_tag table',true),
  ('Add missing dashboard_uid and org_id to star',true),
  ('create data_source table',true),
  ('add index data_source.account_id',true),
  ('add unique index data_source.account_id_name',true),
  ('drop index IDX_data_source_account_id - v1',true),
  ('drop index UQE_data_source_account_id_name - v1',true),
  ('Rename table data_source to data_source_v1 - v1',true),
  ('create data_source table v2',true),
  ('create index IDX_data_source_org_id - v2',true),
  ('create index UQE_data_source_org_id_name - v2',true),
  ('Drop old table data_source_v1 #2',true),
  ('Add column with_credentials',true),
  ('Add secure json data column',true),
  ('Update data_source table charset',true),
  ('Update initial version to 1',true),
  ('Add read_only data column',true),
  ('Migrate logging ds to loki ds',true),
  ('Update json_data with nulls',true),
  ('Add uid column',true),
  ('Update uid value',true),
  ('Add unique index datasource_org_id_uid',true),
  ('add unique index datasource_org_id_is_default',true),
  ('Add is_prunable column',true),
  ('Add api_version column',true),
  ('Update secure_json_data column to MediumText',true),
  ('create api_key table',true),
  ('add index api_key.account_id',true),
  ('add index api_key.key',true),
  ('add index api_key.account_id_name',true),
  ('drop index IDX_api_key_account_id - v1',true),
  ('drop index UQE_api_key_key - v1',true),
  ('drop index UQE_api_key_account_id_name - v1',true),
  ('Rename table api_key to api_key_v1 - v1',true),
  ('create api_key table v2',true),
  ('create index IDX_api_key_org_id - v2',true),
  ('create index UQE_api_key_key - v2',true),
  ('create index UQE_api_key_org_id_name - v2',true),
  ('copy api_key v1 to v2',true),
  ('Drop old table api_key_v1',true),
  ('Update api_key table charset',true),
  ('Add expires to api_key table',true),
  ('Add service account foreign key',true),
  ('set service account foreign key to nil if 0',true),
  ('Add last_used_at to api_key table',true),
  ('Add is_revoked column to api_key table',true),
  ('create dashboard_snapshot table v4',true),
  ('drop table dashboard_snapshot_v4 #1',true),
  ('create dashboard_snapshot table v5 #2',true),
  ('create index UQE_dashboard_snapshot_key - v5',true),
  ('create index UQE_dashboard_snapshot_delete_key - v5',true),
  ('create index IDX_dashboard_snapshot_user_id - v5',true),
  ('alter dashboard_snapshot to mediumtext v2',true),
  ('Update dashboard_snapshot table charset',true),
  ('Add column external_delete_url to dashboard_snapshots table',true),
  ('Add encrypted dashboard json column',true),
  ('Change dashboard_encrypted column to MEDIUMBytes',true),
  ('create quota table v1',true),
  ('create index UQE_quota_org_id_user_id_target - v1',true),
  ('Update quota table charset',true),
  ('create plugin_setting table',true),
  ('create index UQE_plugin_setting_org_id_plugin_id - v1',true),
  ('Add column plugin_version to plugin_settings',true),
  ('Update plugin_setting table charset',true),
  ('update NULL org_id to 1',true),
  ('make org_id NOT NULL and DEFAULT VALUE 1',true),
  ('create session table',true),
  ('Drop old table playlist table',true),
  ('Drop old table playlist_item table',true),
  ('create playlist table v2',true),
  ('create playlist item table v2',true),
  ('Update playlist table charset',true),
  ('Update playlist_item table charset',true),
  ('Add playlist column created_at',true),
  ('Add playlist column updated_at',true),
  ('drop preferences table v2',true),
  ('drop preferences table v3',true),
  ('create preferences table v3',true),
  ('Update preferences table charset',true),
  ('Add column team_id in preferences',true),
  ('Update team_id column values in preferences',true),
  ('Add column week_start in preferences',true),
  ('Add column preferences.json_data',true),
  ('alter preferences.json_data to mediumtext v1',true),
  ('Add preferences index org_id',true),
  ('Add preferences index user_id',true),
  ('Add home_dashboard_uid column to preferences table',true),
  ('Add missing dashboard_uid to preferences table',true),
  ('create alert table v1',true),
  ('add index alert org_id & id ',true),
  ('add index alert state',true),
  ('add index alert dashboard_id',true),
  ('Create alert_rule_tag table v1',true),
  ('Add unique index alert_rule_tag.alert_id_tag_id',true),
  ('drop index UQE_alert_rule_tag_alert_id_tag_id - v1',true),
  ('Rename table alert_rule_tag to alert_rule_tag_v1 - v1',true),
  ('Create alert_rule_tag table v2',true),
  ('create index UQE_alert_rule_tag_alert_id_tag_id - Add unique index alert_rule_tag.alert_id_tag_id V2',true),
  ('copy alert_rule_tag v1 to v2',true),
  ('drop table alert_rule_tag_v1',true),
  ('create alert_notification table v1',true),
  ('Add column is_default',true),
  ('Add column frequency',true),
  ('Add column send_reminder',true),
  ('Add column disable_resolve_message',true),
  ('add index alert_notification org_id & name',true),
  ('Update alert table charset',true),
  ('Update alert_notification table charset',true),
  ('create notification_journal table v1',true),
  ('add index notification_journal org_id & alert_id & notifier_id',true),
  ('drop alert_notification_journal',true),
  ('create alert_notification_state table v1',true),
  ('add index alert_notification_state org_id & alert_id & notifier_id',true),
  ('Add for to alert table',true),
  ('Add column uid in alert_notification',true),
  ('Update uid column values in alert_notification',true),
  ('Add unique index alert_notification_org_id_uid',true),
  ('Remove unique index org_id_name',true),
  ('Add column secure_settings in alert_notification',true),
  ('alter alert.settings to mediumtext',true),
  ('Add non-unique index alert_notification_state_alert_id',true),
  ('Add non-unique index alert_rule_tag_alert_id',true),
  ('Drop old annotation table v4',true),
  ('create annotation table v5',true),
  ('add index annotation 0 v3',true),
  ('add index annotation 1 v3',true),
  ('add index annotation 2 v3',true),
  ('add index annotation 3 v3',true),
  ('add index annotation 4 v3',true),
  ('Update annotation table charset',true),
  ('Add column region_id to annotation table',true),
  ('Drop category_id index',true),
  ('Add column tags to annotation table',true),
  ('Create annotation_tag table v2',true),
  ('Add unique index annotation_tag.annotation_id_tag_id',true),
  ('drop index UQE_annotation_tag_annotation_id_tag_id - v2',true),
  ('Rename table annotation_tag to annotation_tag_v2 - v2',true),
  ('Create annotation_tag table v3',true),
  ('create index UQE_annotation_tag_annotation_id_tag_id - Add unique index annotation_tag.annotation_id_tag_id V3',true),
  ('copy annotation_tag v2 to v3',true),
  ('drop table annotation_tag_v2',true),
  ('Update alert annotations and set Text to empty',true),
  ('Add created time to annotation table',true),
  ('Add updated time to annotation table',true),
  ('Add index for created in annotation table',true),
  ('Add index for updated in annotation table',true),
  ('Convert existing annotations from seconds to milliseconds',true),
  ('Add epoch_end column',true),
  ('Add index for epoch_end',true),
  ('Make epoch_end the same as epoch',true),
  ('Move region to single row',true),
  ('Remove index org_id_epoch from annotation table',true),
  ('Remove index org_id_dashboard_id_panel_id_epoch from annotation table',true),
  ('Add index for org_id_dashboard_id_epoch_end_epoch on annotation table',true),
  ('Add index for org_id_epoch_end_epoch on annotation table',true),
  ('Remove index org_id_epoch_epoch_end from annotation table',true),
  ('Add index for alert_id on annotation table',true),
  ('Increase tags column to length 4096',true),
  ('Increase prev_state column to length 40 not null',true),
  ('Increase new_state column to length 40 not null',true),
  ('Add dashboard_uid column to annotation table',true),
  ('Add missing dashboard_uid to annotation table',true),
  ('create test_data table',true),
  ('create dashboard_version table v1',true),
  ('add index dashboard_version.dashboard_id',true),
  ('add unique index dashboard_version.dashboard_id and dashboard_version.version',true),
  ('Set dashboard version to 1 where 0',true),
  ('save existing dashboard data in dashboard_version table v1',true),
  ('alter dashboard_version.data to mediumtext v1',true),
  ('Add apiVersion for dashboard_version',true),
  ('create team table',true),
  ('add index team.org_id',true),
  ('add unique index team_org_id_name',true),
  ('Add column uid in team',true),
  ('Update uid column values in team',true),
  ('Add unique index team_org_id_uid',true),
  ('Add column external_uid in team',true),
  ('Add column is_provisioned in team',true),
  ('create team member table',true),
  ('add index team_member.org_id',true),
  ('add unique index team_member_org_id_team_id_user_id',true),
  ('add index team_member.team_id',true),
  ('Add column email to team table',true),
  ('Add column external to team_member table',true),
  ('Add column permission to team_member table',true),
  ('add unique index team_member_user_id_org_id',true),
  ('create dashboard acl table',true),
  ('add index dashboard_acl_dashboard_id',true),
  ('add unique index dashboard_acl_dashboard_id_user_id',true),
  ('add unique index dashboard_acl_dashboard_id_team_id',true),
  ('add index dashboard_acl_user_id',true),
  ('add index dashboard_acl_team_id',true),
  ('add index dashboard_acl_org_id_role',true),
  ('add index dashboard_permission',true),
  ('save default acl rules in dashboard_acl table',true),
  ('delete acl rules for deleted dashboards and folders',true),
  ('create tag table',true),
  ('add index tag.key_value',true),
  ('create login attempt table',true),
  ('add index login_attempt.username',true),
  ('drop index IDX_login_attempt_username - v1',true),
  ('Rename table login_attempt to login_attempt_tmp_qwerty - v1',true),
  ('create login_attempt v2',true),
  ('create index IDX_login_attempt_username - v2',true),
  ('copy login_attempt v1 to v2',true),
  ('drop login_attempt_tmp_qwerty',true),
  ('increase login_attempt.ip_address column length for IPv6 support',true),
  ('alter table login_attempt alter column created type to bigint',true),
  ('create user auth table',true),
  ('create index IDX_user_auth_auth_module_auth_id - v1',true),
  ('alter user_auth.auth_id to length 190',true),
  ('Add OAuth access token to user_auth',true),
  ('Add OAuth refresh token to user_auth',true),
  ('Add OAuth token type to user_auth',true),
  ('Add OAuth expiry to user_auth',true),
  ('Add index to user_id column in user_auth',true),
  ('Add OAuth ID token to user_auth',true),
  ('Add user_unique_id to user_auth',true),
  ('create server_lock table',true),
  ('add index server_lock.operation_uid',true),
  ('create user auth token table',true),
  ('add unique index user_auth_token.auth_token',true),
  ('add unique index user_auth_token.prev_auth_token',true),
  ('add index user_auth_token.user_id',true),
  ('Add revoked_at to the user auth token',true),
  ('add index user_auth_token.revoked_at',true),
  ('add external_session_id to user_auth_token',true),
  ('create cache_data table',true),
  ('add unique index cache_data.cache_key',true),
  ('create short_url table v1',true),
  ('add index short_url.org_id-uid',true),
  ('alter table short_url alter column created_by type to bigint',true),
  ('delete alert_definition table',true),
  ('recreate alert_definition table',true),
  ('add index in alert_definition on org_id and title columns',true),
  ('add index in alert_definition on org_id and uid columns',true),
  ('alter alert_definition table data column to mediumtext in mysql',true),
  ('drop index in alert_definition on org_id and title columns',true),
  ('drop index in alert_definition on org_id and uid columns',true),
  ('add unique index in alert_definition on org_id and title columns',true),
  ('add unique index in alert_definition on org_id and uid columns',true),
  ('Add column paused in alert_definition',true),
  ('drop alert_definition table',true),
  ('delete alert_definition_version table',true),
  ('recreate alert_definition_version table',true),
  ('add index in alert_definition_version table on alert_definition_id and version columns',true),
  ('add index in alert_definition_version table on alert_definition_uid and version columns',true),
  ('alter alert_definition_version table data column to mediumtext in mysql',true),
  ('drop alert_definition_version table',true),
  ('create alert_instance table',true),
  ('add index in alert_instance table on def_org_id, def_uid and current_state columns',true),
  ('add index in alert_instance table on def_org_id, current_state columns',true),
  ('add column current_state_end to alert_instance',true),
  ('remove index def_org_id, def_uid, current_state on alert_instance',true),
  ('remove index def_org_id, current_state on alert_instance',true),
  ('rename def_org_id to rule_org_id in alert_instance',true),
  ('rename def_uid to rule_uid in alert_instance',true),
  ('add index rule_org_id, rule_uid, current_state on alert_instance',true),
  ('add index rule_org_id, current_state on alert_instance',true),
  ('add current_reason column related to current_state',true),
  ('add result_fingerprint column to alert_instance',true),
  ('create alert_rule table',true),
  ('add index in alert_rule on org_id and title columns',true),
  ('add index in alert_rule on org_id and uid columns',true),
  ('add index in alert_rule on org_id, namespace_uid, group_uid columns',true),
  ('alter alert_rule table data column to mediumtext in mysql',true),
  ('add column for to alert_rule',true),
  ('add column annotations to alert_rule',true),
  ('add column labels to alert_rule',true),
  ('remove unique index from alert_rule on org_id, title columns',true),
  ('add index in alert_rule on org_id, namespase_uid and title columns',true),
  ('add dashboard_uid column to alert_rule',true),
  ('add panel_id column to alert_rule',true),
  ('add index in alert_rule on org_id, dashboard_uid and panel_id columns',true),
  ('add rule_group_idx column to alert_rule',true),
  ('add is_paused column to alert_rule table',true),
  ('fix is_paused column for alert_rule table',true),
  ('alter table alert_rule alter column rule_group_idx type to bigint',true),
  ('create alert_rule_version table',true),
  ('add index in alert_rule_version table on rule_org_id, rule_uid and version columns',true),
  ('add index in alert_rule_version table on rule_org_id, rule_namespace_uid and rule_group columns',true),
  ('alter alert_rule_version table data column to mediumtext in mysql',true),
  ('add column for to alert_rule_version',true),
  ('add column annotations to alert_rule_version',true),
  ('add column labels to alert_rule_version',true),
  ('add rule_group_idx column to alert_rule_version',true),
  ('add is_paused column to alert_rule_versions table',true),
  ('fix is_paused column for alert_rule_version table',true),
  ('alter table alert_rule_version alter column rule_group_idx type to bigint',true),
  ('create_alert_configuration_table',true),
  ('Add column default in alert_configuration',true),
  ('alert alert_configuration alertmanager_configuration column from Text to MEDIUMText if mysql',true),
  ('add column org_id in alert_configuration',true),
  ('add index in alert_configuration table on org_id column',true),
  ('add configuration_hash column to alert_configuration',true),
  ('create_ngalert_configuration_table',true),
  ('add index in ngalert_configuration on org_id column',true),
  ('add column send_alerts_to in ngalert_configuration',true),
  ('create provenance_type table',true),
  ('add index to uniquify (record_key, record_type, org_id) columns',true),
  ('create alert_image table',true),
  ('add unique index on token to alert_image table',true),
  ('support longer URLs in alert_image table',true),
  ('create_alert_configuration_history_table',true),
  ('drop non-unique orgID index on alert_configuration',true),
  ('drop unique orgID index on alert_configuration if exists',true),
  ('extract alertmanager configuration history to separate table',true),
  ('add unique index on orgID to alert_configuration',true),
  ('add last_applied column to alert_configuration_history',true),
  ('create library_element table v1',true),
  ('add index library_element org_id-folder_id-name-kind',true),
  ('create library_element_connection table v1',true),
  ('add index library_element_connection element_id-kind-connection_id',true),
  ('add unique index library_element org_id_uid',true),
  ('increase max description length to 2048',true),
  ('alter library_element model to mediumtext',true),
  ('add library_element folder uid',true),
  ('populate library_element folder_uid',true),
  ('add index library_element org_id-folder_uid-name-kind',true),
  ('clone move dashboard alerts to unified alerting',true),
  ('create data_keys table',true),
  ('create secrets table',true),
  ('rename data_keys name column to id',true),
  ('add name column into data_keys',true),
  ('copy data_keys id column values into name',true),
  ('rename data_keys name column to label',true),
  ('rename data_keys id column back to name',true),
  ('create kv_store table v1',true),
  ('add index kv_store.org_id-namespace-key',true),
  ('update dashboard_uid and panel_id from existing annotations',true),
  ('create permission table',true),
  ('add unique index permission.role_id',true),
  ('add unique index role_id_action_scope',true),
  ('create role table',true),
  ('add column display_name',true),
  ('add column group_name',true),
  ('add index role.org_id',true),
  ('add unique index role_org_id_name',true),
  ('add index role_org_id_uid',true),
  ('create team role table',true),
  ('add index team_role.org_id',true),
  ('add unique index team_role_org_id_team_id_role_id',true),
  ('add index team_role.team_id',true),
  ('create user role table',true),
  ('add index user_role.org_id',true),
  ('add unique index user_role_org_id_user_id_role_id',true),
  ('add index user_role.user_id',true),
  ('create builtin role table',true),
  ('add index builtin_role.role_id',true),
  ('add index builtin_role.name',true),
  ('Add column org_id to builtin_role table',true),
  ('add index builtin_role.org_id',true),
  ('add unique index builtin_role_org_id_role_id_role',true),
  ('Remove unique index role_org_id_uid',true),
  ('add unique index role.uid',true),
  ('create seed assignment table',true),
  ('add unique index builtin_role_role_name',true),
  ('add column hidden to role table',true),
  ('permission kind migration',true),
  ('permission attribute migration',true),
  ('permission identifier migration',true),
  ('add permission identifier index',true),
  ('add permission action scope role_id index',true),
  ('remove permission role_id action scope index',true),
  ('add group mapping UID column to user_role table',true),
  ('add user_role org ID, user ID, role ID, group mapping UID index',true),
  ('remove user_role org ID, user ID, role ID index',true),
  ('add permission role_id action index',true),
  ('Remove permission role_id index',true),
  ('create query_history table v1',true),
  ('add index query_history.org_id-created_by-datasource_uid',true),
  ('alter table query_history alter column created_by type to bigint',true),
  ('create query_history_details table v1',true),
  ('rbac disabled migrator',true),
  ('teams permissions migration',true),
  ('dashboard permissions',true),
  ('dashboard permissions uid scopes',true),
  ('drop managed folder create actions',true),
  ('alerting notification permissions',true),
  ('create query_history_star table v1',true),
  ('add index query_history.user_id-query_uid',true),
  ('add column org_id in query_history_star',true),
  ('alter table query_history_star_mig column user_id type to bigint',true),
  ('create correlation table v1',true),
  ('add index correlations.uid',true),
  ('add index correlations.source_uid',true),
  ('add correlation config column',true),
  ('drop index IDX_correlation_uid - v1',true),
  ('drop index IDX_correlation_source_uid - v1',true),
  ('Rename table correlation to correlation_tmp_qwerty - v1',true),
  ('create correlation v2',true),
  ('create index IDX_correlation_uid - v2',true),
  ('create index IDX_correlation_source_uid - v2',true),
  ('create index IDX_correlation_org_id - v2',true),
  ('copy correlation v1 to v2',true),
  ('drop correlation_tmp_qwerty',true),
  ('add provisioning column',true),
  ('add type column',true),
  ('create entity_events table',true),
  ('create dashboard public config v1',true),
  ('drop index UQE_dashboard_public_config_uid - v1',true),
  ('drop index IDX_dashboard_public_config_org_id_dashboard_uid - v1',true),
  ('Drop old dashboard public config table',true),
  ('recreate dashboard public config v1',true),
  ('create index UQE_dashboard_public_config_uid - v1',true),
  ('create index IDX_dashboard_public_config_org_id_dashboard_uid - v1',true),
  ('drop index UQE_dashboard_public_config_uid - v2',true),
  ('drop index IDX_dashboard_public_config_org_id_dashboard_uid - v2',true),
  ('Drop public config table',true),
  ('Recreate dashboard public config v2',true),
  ('create index UQE_dashboard_public_config_uid - v2',true),
  ('create index IDX_dashboard_public_config_org_id_dashboard_uid - v2',true),
  ('create index UQE_dashboard_public_config_access_token - v2',true),
  ('Rename table dashboard_public_config to dashboard_public - v2',true),
  ('add annotations_enabled column',true),
  ('add time_selection_enabled column',true),
  ('delete orphaned public dashboards',true),
  ('add share column',true),
  ('backfill empty share column fields with default of public',true),
  ('create file table',true),
  ('file table idx: path natural pk',true),
  ('file table idx: parent_folder_path_hash fast folder retrieval',true),
  ('create file_meta table',true),
  ('file table idx: path key',true),
  ('set path collation in file table',true),
  ('migrate contents column to mediumblob for MySQL',true),
  ('managed permissions migration',true),
  ('managed folder permissions alert actions migration',true),
  ('RBAC action name migrator',true),
  ('Add UID column to playlist',true),
  ('Update uid column values in playlist',true),
  ('Add index for uid in playlist',true),
  ('update group index for alert rules',true),
  ('managed folder permissions alert actions repeated migration',true),
  ('admin only folder/dashboard permission',true),
  ('add action column to seed_assignment',true),
  ('add scope column to seed_assignment',true),
  ('remove unique index builtin_role_role_name before nullable update',true),
  ('update seed_assignment role_name column to nullable',true),
  ('add unique index builtin_role_name back',true),
  ('add unique index builtin_role_action_scope',true),
  ('add primary key to seed_assigment',true),
  ('add origin column to seed_assignment',true),
  ('add origin to plugin seed_assignment',true),
  ('prevent seeding OnCall access',true),
  ('managed folder permissions alert actions repeated fixed migration',true),
  ('managed folder permissions library panel actions migration',true),
  ('migrate external alertmanagers to datsourcse',true),
  ('create folder table',true),
  ('Add index for parent_uid',true),
  ('Add unique index for folder.uid and folder.org_id',true),
  ('Update folder title length',true),
  ('Add unique index for folder.title and folder.parent_uid',true),
  ('Remove unique index for folder.title and folder.parent_uid',true),
  ('Add unique index for title, parent_uid, and org_id',true),
  ('Sync dashboard and folder table',true),
  ('Remove ghost folders from the folder table',true),
  ('Remove unique index UQE_folder_uid_org_id',true),
  ('Add unique index UQE_folder_org_id_uid',true),
  ('Remove unique index UQE_folder_title_parent_uid_org_id',true),
  ('Add unique index UQE_folder_org_id_parent_uid_title',true),
  ('Remove index IDX_folder_parent_uid_org_id',true),
  ('Remove unique index UQE_folder_org_id_parent_uid_title',true),
  ('Add index IDX_folder_org_id_parent_uid',true),
  ('create anon_device table',true),
  ('add unique index anon_device.device_id',true),
  ('add index anon_device.updated_at',true),
  ('create signing_key table',true),
  ('add unique index signing_key.key_id',true),
  ('set legacy alert migration status in kvstore',true),
  ('migrate record of created folders during legacy migration to kvstore',true),
  ('Add folder_uid for dashboard',true),
  ('Populate dashboard folder_uid column',true),
  ('Add unique index for dashboard_org_id_folder_uid_title',true),
  ('Delete unique index for dashboard_org_id_folder_id_title',true),
  ('Delete unique index for dashboard_org_id_folder_uid_title',true),
  ('Add unique index for dashboard_org_id_folder_uid_title_is_folder',true),
  ('Restore index for dashboard_org_id_folder_id_title',true),
  ('Remove unique index for dashboard_org_id_folder_uid_title_is_folder',true),
  ('create sso_setting table',true),
  ('copy kvstore migration status to each org',true),
  ('add back entry for orgid=0 migrated status',true),
  ('managed dashboard permissions annotation actions migration',true),
  ('create cloud_migration table v1',true),
  ('create cloud_migration_run table v1',true),
  ('add stack_id column',true),
  ('add region_slug column',true),
  ('add cluster_slug column',true),
  ('add migration uid column',true),
  ('Update uid column values for migration',true),
  ('Add unique index migration_uid',true),
  ('add migration run uid column',true),
  ('Update uid column values for migration run',true),
  ('Add unique index migration_run_uid',true),
  ('Rename table cloud_migration to cloud_migration_session_tmp_qwerty - v1',true),
  ('create cloud_migration_session v2',true),
  ('create index UQE_cloud_migration_session_uid - v2',true),
  ('copy cloud_migration_session v1 to v2',true),
  ('drop cloud_migration_session_tmp_qwerty',true),
  ('Rename table cloud_migration_run to cloud_migration_snapshot_tmp_qwerty - v1',true),
  ('create cloud_migration_snapshot v2',true),
  ('create index UQE_cloud_migration_snapshot_uid - v2',true),
  ('copy cloud_migration_snapshot v1 to v2',true),
  ('drop cloud_migration_snapshot_tmp_qwerty',true),
  ('add snapshot upload_url column',true),
  ('add snapshot status column',true),
  ('add snapshot local_directory column',true),
  ('add snapshot gms_snapshot_uid column',true),
  ('add snapshot encryption_key column',true),
  ('add snapshot error_string column',true),
  ('create cloud_migration_resource table v1',true),
  ('delete cloud_migration_snapshot.result column',true),
  ('add cloud_migration_resource.name column',true),
  ('add cloud_migration_resource.parent_name column',true),
  ('add cloud_migration_session.org_id column',true),
  ('add cloud_migration_resource.error_code column',true),
  ('increase resource_uid column length',true),
  ('create cloud_migration_snapshot_partition table v1',true),
  ('add cloud_migration_snapshot_partition srp_unique index',true),
  ('add resource_storage_type column to cloud_migration_snapshot table',true),
  ('add encryption_algo column to cloud_migration_snapshot table',true),
  ('add metadata column to cloud_migration_snapshot table',true),
  ('add public_key column to cloud_migration_snapshot table',true),
  ('alter kv_store.value to longtext',true),
  ('add notification_settings column to alert_rule table',true),
  ('add notification_settings column to alert_rule_version table',true),
  ('removing scope from alert.instances:read action migration',true),
  ('managed folder permissions alerting silences actions migration',true),
  ('add record column to alert_rule table',true),
  ('add record column to alert_rule_version table',true),
  ('add resolved_at column to alert_instance table',true),
  ('add last_sent_at column to alert_instance table',true),
  ('Add scope to alert.notifications.receivers:read and alert.notifications.receivers.secrets:read',true),
  ('add metadata column to alert_rule table',true),
  ('add metadata column to alert_rule_version table',true),
  ('delete orphaned service account permissions',true),
  ('adding action set permissions',true),
  ('create user_external_session table',true),
  ('increase name_id column length to 1024',true),
  ('increase session_id column length to 1024',true),
  ('remove scope from alert.notifications.receivers:create',true),
  ('add created_by column to alert_rule_version table',true),
  ('add updated_by column to alert_rule table',true),
  ('add alert_rule_state table',true),
  ('add index to alert_rule_state on org_id and rule_uid columns',true),
  ('add guid column to alert_rule table',true),
  ('add rule_guid column to alert_rule_version table',true),
  ('cleanup alert_rule_version table',true),
  ('populate rule guid in alert rule table',true),
  ('drop index in alert_rule_version table on rule_org_id, rule_uid and version columns',true),
  ('add index in alert_rule_version table on rule_org_id, rule_uid, rule_guid and version columns',true),
  ('add index in alert_rule_version table on rule_guid and version columns',true),
  ('add index in alert_rule table on guid columns',true),
  ('add keep_firing_for column to alert_rule',true),
  ('add keep_firing_for column to alert_rule_version',true),
  ('add missing_series_evals_to_resolve column to alert_rule',true),
  ('add missing_series_evals_to_resolve column to alert_rule_version',true),
  ('remove the datasources:drilldown action',true),
  ('remove title in folder unique index',true),
  ('add fired_at column to alert_instance table',true),
  ('Change dashboard_encrypted column to MEDIUMBLOB',true),
  ('Update alert annotations and set TEXT to empty',true);
`

func readSnapshotSQL() ([]sqlFile, error) {
	entries, err := snapshotFS.ReadDir("snapshot")
	if err != nil {
		return nil, xerrors.WithStackTrace(fmt.Errorf("snapshot: read dir: %v", err))
	}

	sqlFiles := make([]sqlFile, 0)
	for _, e := range entries {
		bb, err := snapshotFS.ReadFile("snapshot/" + e.Name())
		if err != nil {
			return nil, xerrors.WithStackTrace(fmt.Errorf("snapshot: read %s: %v", e.Name(), err))
		}
		sqlFiles = append(sqlFiles, sqlFile{
			name:    e.Name(),
			content: xstring.FromBytes(bb),
		})
	}

	return sqlFiles, nil
}

func applySnapshot(ctx context.Context, db *ydb.Driver, migrationLogTableName string) error {
	sqlFiles, err := readSnapshotSQL()
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	for _, sqlFile := range sqlFiles {
		if err := db.Query().Exec(ctx, sqlFile.content); err != nil {
			return xerrors.WithStackTrace(fmt.Errorf("snapshot: apply %q failed: %v", sqlFile.name, err))
		}
	}

	tmpl, err := template.New("").Parse(createMigrationLogTableTemplate)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	var buffer strings.Builder

	if err := tmpl.Execute(&buffer, struct{ Name string }{migrationLogTableName}); err != nil {
		return xerrors.WithStackTrace(err)
	}

	if err := db.Query().Exec(ctx, strings.ReplaceAll(buffer.String(), "\"", "`")); err != nil {
		return xerrors.WithStackTrace(fmt.Errorf("snapshot: create table %q failed: %v", migrationLogTableName, err))
	}

	tmpl, err = template.New("").Parse(upsertMigrationLogData)
	if err != nil {
		return xerrors.WithStackTrace(err)
	}

	buffer.Reset()

	if err := tmpl.Execute(&buffer, struct{ Name string }{migrationLogTableName}); err != nil {
		return xerrors.WithStackTrace(err)
	}

	if err := db.Query().Exec(ctx, strings.ReplaceAll(buffer.String(), "\"", "`")); err != nil {
		return xerrors.WithStackTrace(fmt.Errorf("snapshot: upsert data into table %q failed: %v", migrationLogTableName, err))
	}

	return nil
}
